// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/klarna-go/v2/pkg/models/shared"
	"net/http"
)

type CreateOrderRequest struct {
	AuthorizationToken      string                          `pathParam:"style=simple,explode=false,name=authorizationToken"`
	CreateOrderRequestInput *shared.CreateOrderRequestInput `request:"mediaType=application/json"`
}

type CreateOrderResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Order was successfully created.
	Order *shared.Order
}
