// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/klarna-go/v2/pkg/models/shared"
	"net/http"
)

type ReadCreditSessionRequest struct {
	// session_id
	SessionID string `pathParam:"style=simple,explode=false,name=session_id"`
}

type ReadCreditSessionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// successful operation
	SessionRead *shared.SessionRead
}
