// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/klarna-go/v2/pkg/models/shared"
	"net/http"
)

type UpdateCreditSessionRequest struct {
	// session_request
	SessionInput shared.SessionInput `request:"mediaType=application/json"`
	// session_id
	SessionID string `pathParam:"style=simple,explode=false,name=session_id"`
}

type UpdateCreditSessionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
