// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Address struct {
	// ‘Attn.’ (if applicable). Only applicable for B2B customers.
	Attention *string `json:"attention,omitempty"`
	// Customer’s city.
	City *string `json:"city,omitempty"`
	// Customer’s country. This value overrides the purchase country if they are different. Should follow the standard of ISO 3166 alpha-2. E.g. GB, US, DE, SE.
	Country *string `json:"country,omitempty"`
	// Customer’s email address.
	Email *string `json:"email,omitempty"`
	// Customers family name in UTF-8 encoding.
	// Cannot be only numbers, must be more than 1 character.
	// Allowed special characters: -'’.
	// More information can be found [in this link](https://docs.klarna.com/klarna-payments/in-depth-knowledge/customer-data-requirements/#details-needed-per-market)
	FamilyName *string `json:"family_name,omitempty"`
	// Customers given name in UTF-8 encoding.
	// Cannot be only numbers, must be more than 1 character.
	// Allowed special characters: -'’.
	// More information can be found [in this link](https://docs.klarna.com/klarna-payments/in-depth-knowledge/customer-data-requirements/#details-needed-per-market)
	GivenName *string `json:"given_name,omitempty"`
	// Organization name (if applicable). Only applicable for B2B customers.
	OrganizationName *string `json:"organization_name,omitempty"`
	// Phone number. Preferably a mobile phone number.
	Phone *string `json:"phone,omitempty"`
	// Customer’s postal code. Validation according to Universal Postal Union addressing systems.
	// E.g. 12345, W1G OPW.
	PostalCode *string `json:"postal_code,omitempty"`
	// Customer’s region or state - Mandatory for US and AU market. Validations according to ISO 3166-2 format, e.g. OH, NJ, etc.
	Region *string `json:"region,omitempty"`
	// Customer’s street address. Regional formatting is required, as follows:
	// UK/US/FR: 33 Cavendish Square
	// Rest of EU: De Ruijterkade 7
	StreetAddress *string `json:"street_address,omitempty"`
	// Customer’s street address. Second Line.
	StreetAddress2 *string `json:"street_address2,omitempty"`
	// Customer’s Title. Allowed values per country:
	// UK - "Mr", "Ms"
	// DE - "Herr", "Frau"
	// AT: "Herr, "Frau"
	// CH: de-CH: "Herr, "Frau" it-CH: "Sig.", "Sig.ra" fr-CH: "M", "Mme"
	// BE: "Dhr.", "Mevr."
	// NL: "Dhr.", "Mevr."
	Title *string `json:"title,omitempty"`
}
