// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AssetUrls struct {
	// URL of the descriptive asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
	Descriptive *string `json:"descriptive,omitempty"`
	// URL of the standard asset. Using this dynamic asset will make sure that any copy update of Klarna will automatically be propagated.
	Standard *string `json:"standard,omitempty"`
}
