// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Attachment struct {
	// The content of the extra merchant data should be presented as a string inside this property. The body should be an object containing any of the keys and sub-objects described below serialized to JSON. More information on that object can be found [here](https://developers.klarna.com/api/#attachment-schema).
	Body string `json:"body"`
	// The content type of the body. It is usually represented as "application/vnd.klarna.internal.emd-v2+json"
	ContentType string `json:"content_type"`
}
