// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateOrderRequestInput struct {
	// Allow merchant to trigger auto capturing.
	AutoCapture    *bool    `json:"auto_capture,omitempty"`
	BillingAddress *Address `json:"billing_address,omitempty"`
	// Promo codes - The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase. Discuss with the delivery manager to know about the promo codes that will be configured for your account. The feature could also be used to provide promotional offers to specific customers (eg: 0% financing). Please be informed that the usage of this feature can have commercial implications.
	CustomPaymentMethodIds []string  `json:"custom_payment_method_ids,omitempty"`
	Customer               *Customer `json:"customer,omitempty"`
	// Used to define the language and region of the customer. The locale follows the format of [RFC 1766](https://datatracker.ietf.org/doc/rfc1766/), meaning its value consists of language-country.
	// Read more on **[Supported Locals and Currencies](https://docs.klarna.com/klarna-payments/in-depth-knowledge/puchase-countries-currencies-locales/)**.
	Locale *string `json:"locale,omitempty"`
	// Pass through field to send any information about the order to be used later for reference while retrieving the order details (max 6000 characters)
	MerchantData *string `json:"merchant_data,omitempty"`
	// Used for storing merchant's internal order number or other reference.
	MerchantReference1 *string `json:"merchant_reference1,omitempty"`
	// Used for storing merchant's internal order number or other reference. The value is available in the settlement files. (max 255 characters).
	MerchantReference2 *string       `json:"merchant_reference2,omitempty"`
	MerchantUrls       *MerchantUrls `json:"merchant_urls,omitempty"`
	// Total amount of the order including tax and any available discounts. The value should be in non-negative minor units. Eg: 25 Euros should be 2500.
	OrderAmount int64 `json:"order_amount"`
	// The array containing list of line items that are part of this order. Maximum of 1000 line items could be processed in a single order.
	OrderLines []OrderLine `json:"order_lines"`
	// Total tax amount of the order. The value should be in non-negative minor units. Eg: 25 Euros should be 2500.
	OrderTaxAmount *int64 `json:"order_tax_amount,omitempty"`
	// The purchase country of the customer. The billing country always overrides purchase country if the values are different. Formatted according to ISO 3166 alpha-2 standard, e.g. GB, SE, DE, US, etc.
	PurchaseCountry string `json:"purchase_country"`
	// The purchase currency of the order. Formatted according to ISO 4217 standard, e.g. USD, EUR, SEK, GBP, etc.
	PurchaseCurrency string   `json:"purchase_currency"`
	ShippingAddress  *Address `json:"shipping_address,omitempty"`
}
