// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// CustomerReadOrganizationEntityTypeEnum - Organization entity type. Only applicable for B2B customers.
type CustomerReadOrganizationEntityTypeEnum string

const (
	CustomerReadOrganizationEntityTypeEnumLimitedCompany                   CustomerReadOrganizationEntityTypeEnum = "LIMITED_COMPANY"
	CustomerReadOrganizationEntityTypeEnumPublicLimitedCompany             CustomerReadOrganizationEntityTypeEnum = "PUBLIC_LIMITED_COMPANY"
	CustomerReadOrganizationEntityTypeEnumEntrepreneurialCompany           CustomerReadOrganizationEntityTypeEnum = "ENTREPRENEURIAL_COMPANY"
	CustomerReadOrganizationEntityTypeEnumLimitedPartnershipLimitedCompany CustomerReadOrganizationEntityTypeEnum = "LIMITED_PARTNERSHIP_LIMITED_COMPANY"
	CustomerReadOrganizationEntityTypeEnumLimitedPartnership               CustomerReadOrganizationEntityTypeEnum = "LIMITED_PARTNERSHIP"
	CustomerReadOrganizationEntityTypeEnumGeneralPartnership               CustomerReadOrganizationEntityTypeEnum = "GENERAL_PARTNERSHIP"
	CustomerReadOrganizationEntityTypeEnumRegisteredSoleTrader             CustomerReadOrganizationEntityTypeEnum = "REGISTERED_SOLE_TRADER"
	CustomerReadOrganizationEntityTypeEnumSoleTrader                       CustomerReadOrganizationEntityTypeEnum = "SOLE_TRADER"
	CustomerReadOrganizationEntityTypeEnumCivilLawPartnership              CustomerReadOrganizationEntityTypeEnum = "CIVIL_LAW_PARTNERSHIP"
	CustomerReadOrganizationEntityTypeEnumPublicInstitution                CustomerReadOrganizationEntityTypeEnum = "PUBLIC_INSTITUTION"
	CustomerReadOrganizationEntityTypeEnumOther                            CustomerReadOrganizationEntityTypeEnum = "OTHER"
)

func (e CustomerReadOrganizationEntityTypeEnum) ToPointer() *CustomerReadOrganizationEntityTypeEnum {
	return &e
}

func (e *CustomerReadOrganizationEntityTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "LIMITED_COMPANY":
		fallthrough
	case "PUBLIC_LIMITED_COMPANY":
		fallthrough
	case "ENTREPRENEURIAL_COMPANY":
		fallthrough
	case "LIMITED_PARTNERSHIP_LIMITED_COMPANY":
		fallthrough
	case "LIMITED_PARTNERSHIP":
		fallthrough
	case "GENERAL_PARTNERSHIP":
		fallthrough
	case "REGISTERED_SOLE_TRADER":
		fallthrough
	case "SOLE_TRADER":
		fallthrough
	case "CIVIL_LAW_PARTNERSHIP":
		fallthrough
	case "PUBLIC_INSTITUTION":
		fallthrough
	case "OTHER":
		*e = CustomerReadOrganizationEntityTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for CustomerReadOrganizationEntityTypeEnum: %s", s)
	}
}

type CustomerRead struct {
	// Customer’s date of birth. The format is ‘yyyy-mm-dd’
	DateOfBirth *string `json:"date_of_birth,omitempty"`
	// Customer’s gender - ‘male’ or ‘female’
	Gender *string `json:"gender,omitempty"`
	// Organization entity type. Only applicable for B2B customers.
	OrganizationEntityType *CustomerReadOrganizationEntityTypeEnum `json:"organization_entity_type,omitempty"`
	// Organization registration id. Only applicable for B2B customers.
	OrganizationRegistrationID *string `json:"organization_registration_id,omitempty"`
	// Customer’s Title. Allowed values per country:
	// UK - "Mr", "Ms"
	// DE - "Herr", "Frau"
	// AT: "Herr, "Frau"
	// CH: de-CH: "Herr, "Frau" it-CH: "Sig.", "Sig.ra" fr-CH: "M", "Mme"
	// BE: "Dhr.", "Mevr."
	// NL: "Dhr.", "Mevr."
	Title *string `json:"title,omitempty"`
	// Type of customer in the session. If nothing is added, a B2C session will be the default. If it is a b2b-session, you should enter organization to trigger a B2B session.
	Type *string `json:"type,omitempty"`
	// VAT ID. Only applicable for B2B customers.
	VatID *string `json:"vat_id,omitempty"`
}
