// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CustomerReadCreateToken struct {
	// Customer’s date of birth. The format is ‘yyyy-mm-dd’
	DateOfBirth *string `json:"date_of_birth,omitempty"`
	// Customer’s gender - ‘male’ or ‘female’
	Gender *string `json:"gender,omitempty"`
}
