// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ErrorV2 - We were unable to create a customer token with the provided data. Some field constraint was violated.
type ErrorV2 struct {
	AuthorizedPaymentMethod *AuthorizedPaymentMethod `json:"authorized_payment_method,omitempty"`
	CorrelationID           *string                  `json:"correlation_id,omitempty"`
	ErrorCode               *string                  `json:"error_code,omitempty"`
	ErrorMessages           []string                 `json:"error_messages,omitempty"`
	FraudStatus             *string                  `json:"fraud_status,omitempty"`
	Reason                  *string                  `json:"reason,omitempty"`
}
