// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MerchantUrls struct {
	// URL for receiving the authorization token when payment is completed. Used for Authorization Callback.
	Authorization *string `json:"authorization,omitempty"`
	// URL of the merchant confirmation page. The consumer will be redirected back to the confirmation page if the consumer is sent to the redirect URL after placing the order. Insert {session.id} and/or {order.id} as placeholder to connect either of those IDs to the URL(max 2000 characters).
	Confirmation *string `json:"confirmation,omitempty"`
	// URL for notifications on pending orders. Insert {session.id} and/or {order.id} as placeholder to connect either of those IDs to the URL (max 2000 characters).
	Notification *string `json:"notification,omitempty"`
	// URL that will be requested when an order is completed. Should be different than checkout and confirmation URLs. Insert {session.id} and/or {order.id} as placeholder to connect either of those IDs to the URL (max 2000 characters).
	Push *string `json:"push,omitempty"`
}
