// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Options struct {
	// Color for the border of elements within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
	ColorBorder *string `json:"color_border,omitempty"`
	// Color for the border of elements within the iFrame when selected by the customer. Value should be a CSS hex color, e.g. "#FF9900"
	ColorBorderSelected *string `json:"color_border_selected,omitempty"`
	// Color for the bullet points within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
	ColorDetails *string `json:"color_details,omitempty"`
	// Color for the texts within the iFrame. Value should be a CSS hex color, e.g. "#FF9900"
	ColorText *string `json:"color_text,omitempty"`
	// Radius for the border of elements within the iFrame.
	RadiusBorder *string `json:"radius_border,omitempty"`
}
