// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type OrderLine struct {
	// URL to an image that can be later embedded in communications between Klarna and the customer. (max 1024 characters).
	//  A minimum of 250x250 px resolution is recommended for the image to look good in the Klarna app, and below 50x50 px won't even show. We recommend using a good sized image (650x650 px or more), however the file size must not exceed 12MB.
	ImageURL *string `json:"image_url,omitempty"`
	// Used for storing merchant's internal order number or other reference. Pass through field. (max 1024 characters)
	MerchantData *string `json:"merchant_data,omitempty"`
	// Descriptive name of the order line item.
	Name               string              `json:"name"`
	ProductIdentifiers *ProductIdentifiers `json:"product_identifiers,omitempty"`
	// URL to the product in the merchant’s webshop that can be later used in communications between Klarna and the customer. (max 1024 characters)
	ProductURL *string `json:"product_url,omitempty"`
	// Quantity of the order line item. Must be a non-negative number.
	Quantity int64 `json:"quantity"`
	// Unit used to describe the quantity, e.g. kg, pcs, etc. If defined the value has to be 1-8 characters.
	QuantityUnit *string `json:"quantity_unit,omitempty"`
	// Client facing article number, SKU or similar. Max length is 256 characters.
	Reference    *string       `json:"reference,omitempty"`
	Subscription *Subscription `json:"subscription,omitempty"`
	// Tax rate of the order line. Non-negative value. The percentage value is represented with two implicit decimals. I.e 1900 = 19%.
	TaxRate *int64 `json:"tax_rate,omitempty"`
	// Total amount of the order line. Must be defined as minor units. Includes tax and discount. Eg: 2500=25 euros
	// Value = (quantity x unit_price) - total_discount_amount.
	// (max value: 100000000)
	TotalAmount int64 `json:"total_amount"`
	// Non-negative minor units. Includes tax. Eg: 500=5 euros
	TotalDiscountAmount *int64 `json:"total_discount_amount,omitempty"`
	// Total tax amount of the order line. Must be within ±1 of total_amount - total_amount 10000 / (10000 + tax_rate). Negative when type is discount.
	TotalTaxAmount *int64 `json:"total_tax_amount,omitempty"`
	// Type of the order line item. The possible values are:
	//
	// physical
	// discount
	// shipping_fee
	// sales_tax
	// digital
	// gift_card
	// store_credit
	// surcharge
	Type *string `json:"type,omitempty"`
	// Price for a single unit of the order line. Must be defined as minor units. Includes tax, excludes discount. (max value: 100000000)
	UnitPrice int64 `json:"unit_price"`
}
