// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"time"
)

// SessionReadAcquiringChannelEnum - The acquiring channel in which the session takes place. Ecommerce is default unless specified. Any other values should be defined in the agreement.
type SessionReadAcquiringChannelEnum string

const (
	SessionReadAcquiringChannelEnumEcommerce SessionReadAcquiringChannelEnum = "ECOMMERCE"
	SessionReadAcquiringChannelEnumInStore   SessionReadAcquiringChannelEnum = "IN_STORE"
	SessionReadAcquiringChannelEnumTelesales SessionReadAcquiringChannelEnum = "TELESALES"
)

func (e SessionReadAcquiringChannelEnum) ToPointer() *SessionReadAcquiringChannelEnum {
	return &e
}

func (e *SessionReadAcquiringChannelEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "ECOMMERCE":
		fallthrough
	case "IN_STORE":
		fallthrough
	case "TELESALES":
		*e = SessionReadAcquiringChannelEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionReadAcquiringChannelEnum: %s", s)
	}
}

// SessionReadIntentEnum - Intent for the session. The field is designed to let partners inform Klarna of the purpose of the customer’s session.
type SessionReadIntentEnum string

const (
	SessionReadIntentEnumBuy            SessionReadIntentEnum = "buy"
	SessionReadIntentEnumTokenize       SessionReadIntentEnum = "tokenize"
	SessionReadIntentEnumBuyAndTokenize SessionReadIntentEnum = "buy_and_tokenize"
)

func (e SessionReadIntentEnum) ToPointer() *SessionReadIntentEnum {
	return &e
}

func (e *SessionReadIntentEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "buy":
		fallthrough
	case "tokenize":
		fallthrough
	case "buy_and_tokenize":
		*e = SessionReadIntentEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionReadIntentEnum: %s", s)
	}
}

// SessionReadStatusEnum - The current status of the session. Possible values: 'complete', 'incomplete' where 'complete' is set when the order has been placed.
type SessionReadStatusEnum string

const (
	SessionReadStatusEnumComplete   SessionReadStatusEnum = "complete"
	SessionReadStatusEnumIncomplete SessionReadStatusEnum = "incomplete"
)

func (e SessionReadStatusEnum) ToPointer() *SessionReadStatusEnum {
	return &e
}

func (e *SessionReadStatusEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "complete":
		fallthrough
	case "incomplete":
		*e = SessionReadStatusEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for SessionReadStatusEnum: %s", s)
	}
}

// SessionRead - successful operation
type SessionRead struct {
	// The acquiring channel in which the session takes place. Ecommerce is default unless specified. Any other values should be defined in the agreement.
	AcquiringChannel *SessionReadAcquiringChannelEnum `json:"acquiring_channel,omitempty"`
	Attachment       *Attachment                      `json:"attachment,omitempty"`
	// Authorization token.
	AuthorizationToken *string  `json:"authorization_token,omitempty"`
	BillingAddress     *Address `json:"billing_address,omitempty"`
	// Token to be passed to the JS client
	ClientToken *string `json:"client_token,omitempty"`
	// Promo codes - The array could be used to define which of the configured payment options within a payment category (pay_later, pay_over_time, etc.) should be shown for this purchase. Discuss with the delivery manager to know about the promo codes that will be configured for your account. The feature could also be used to provide promotional offers to specific customers (eg: 0% financing). Please be informed that the usage of this feature can have commercial implications.
	CustomPaymentMethodIds []string      `json:"custom_payment_method_ids,omitempty"`
	Customer               *CustomerRead `json:"customer,omitempty"`
	// Design package to use in the session. This can only by used if a custom design has been implemented for Klarna Payments and agreed upon in the agreement. It might have a financial impact. Delivery manager will provide the value for the parameter.
	Design *string `json:"design,omitempty"`
	// Session expiration date
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Intent for the session. The field is designed to let partners inform Klarna of the purpose of the customer’s session.
	Intent *SessionReadIntentEnum `json:"intent,omitempty"`
	// Used to define the language and region of the customer. The locale follows the format of [RFC 1766](https://datatracker.ietf.org/doc/rfc1766/), meaning its value consists of language-country.
	// Read more on **[Supported Locals and Currencies](https://docs.klarna.com/klarna-payments/in-depth-knowledge/puchase-countries-currencies-locales/)**.
	Locale *string `json:"locale,omitempty"`
	// Pass through field to send any information about the order to be used later for reference while retrieving the order details (max 6000 characters)
	MerchantData *string `json:"merchant_data,omitempty"`
	// Used for storing merchant's internal order number or other reference.
	MerchantReference1 *string `json:"merchant_reference1,omitempty"`
	// Used for storing merchant's internal order number or other reference. The value is available in the settlement files. (max 255 characters).
	MerchantReference2 *string       `json:"merchant_reference2,omitempty"`
	MerchantUrls       *MerchantUrls `json:"merchant_urls,omitempty"`
	Options            *Options      `json:"options,omitempty"`
	// Total amount of the order including tax and any available discounts. The value should be in non-negative minor units. Eg: 25 Euros should be 2500.
	OrderAmount *int64 `json:"order_amount,omitempty"`
	// The array containing list of line items that are part of this order. Maximum of 1000 line items could be processed in a single order.
	OrderLines []OrderLine `json:"order_lines,omitempty"`
	// Total tax amount of the order. The value should be in non-negative minor units. Eg: 25 Euros should be 2500.
	OrderTaxAmount *int64 `json:"order_tax_amount,omitempty"`
	// Available payment method categories
	PaymentMethodCategories []PaymentMethodCategory `json:"payment_method_categories,omitempty"`
	// The purchase country of the customer. The billing country always overrides purchase country if the values are different. Formatted according to ISO 3166 alpha-2 standard, e.g. GB, SE, DE, US, etc.
	PurchaseCountry *string `json:"purchase_country,omitempty"`
	// The purchase currency of the order. Formatted according to ISO 4217 standard, e.g. USD, EUR, SEK, GBP, etc.
	PurchaseCurrency *string  `json:"purchase_currency,omitempty"`
	ShippingAddress  *Address `json:"shipping_address,omitempty"`
	// The current status of the session. Possible values: 'complete', 'incomplete' where 'complete' is set when the order has been placed.
	Status *SessionReadStatusEnum `json:"status,omitempty"`
}
